name: flutter_single_instance
description: A simple way to check if your application is already running.

version: 1.5.0
repository: https://github.com/necodeIT/flutter_single_instance
platforms:
  linux:
  macos:
  windows:
  ios:
  android:
  web:
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  grpc: ^4.0.1
  json_annotation: ^4.9.0
  logging: ^1.3.0
  path_provider: ^2.0.13
  protobuf: ^3.1.0
  window_manager: ^0.4.3

dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.4
  json_serializable: ^6.9.3
